// legacy
const devices = [
  {
    name: 'iPhone XR',
    width: 414,
    height: 896,
    type: 'jpeg',
  },
  {
    name: 'iPhone XS',
    width: 375,
    height: 812,
    type: 'jpeg',
  },
  {
    name: 'iPhone XS Max',
    width: 414,
    height: 896,
    type: 'jpeg',
  },
  {
    name: 'iPhone X',
    width: 375,
    height: 812,
    type: 'jpeg',
  },
  {
    name: 'iPhone 8 Plus',
    width: 414,
    height: 736,
    type: 'jpeg',
  },
  {
    name: 'iPhone 8',
    width: 375,
    height: 667,
    type: 'jpeg',
  },
  {
    name: 'iPhone 7 Plus',
    width: 414,
    height: 736,
    type: 'jpeg',
  },
  {
    name: 'iPhone 7',
    width: 375,
    height: 667,
    type: 'jpeg',
  },
  {
    name: 'iPhone 6 Plus 6S Plus',
    width: 414,
    height: 736,
    type: 'jpeg',
  },
  {
    name: 'iPhone 6 6S',
    width: 375,
    height: 667,
    type: 'jpeg',
  },
  {
    name: 'iPhone 5',
    width: 320,
    height: 568,
    type: 'jpeg',
  },
  {
    name: 'iPod Touch',
    width: 320,
    height: 568,
    type: 'jpeg',
  },
  {
    name: 'iPad Pro',
    width: 1024,
    height: 1366,
    type: 'jpeg',
  },
  {
    name: 'iPad Third & Fourth Generation',
    width: 768,
    height: 1024,
    type: 'jpeg',
  },
  {
    name: 'iPad Air 1 & 2',
    width: 768,
    height: 1024,
    type: 'jpeg',
  },
  {
    name: 'iPad Mini 2 & 3',
    width: 768,
    height: 1024,
    type: 'jpeg',
  },
  {
    name: 'iPad Mini',
    width: 768,
    height: 1024,
    type: 'jpeg',
  },
  {
    name: 'Nexus 6P',
    width: 412,
    height: 732,
    type: 'jpeg',
  },
  {
    name: 'Nexus 5X',
    width: 412,
    height: 732,
    type: 'jpeg',
  },
  {
    name: 'Google Pixel 3 XL',
    width: 412,
    height: 847,
    type: 'jpeg',
  },
  {
    name: 'Google Pixel 3',
    width: 412,
    height: 824,
    type: 'jpeg',
  },
  {
    name: 'Google Pixel 2 XL',
    width: 412,
    height: 732,
    type: 'jpeg',
  },
  {
    name: 'Google Pixel XL',
    width: 412,
    height: 732,
    type: 'jpeg',
  },
  {
    name: 'Google Pixel',
    width: 412,
    height: 732,
    type: 'jpeg',
  },
  {
    name: 'Samsung Galaxy Note 9',
    width: 360,
    height: 740,
    type: 'jpeg',
  },
  {
    name: 'Samsung Galaxy Note 5',
    width: 480,
    height: 853,
    type: 'jpeg',
  },
  {
    name: 'LG G5',
    width: 480,
    height: 853,
    type: 'jpeg',
  },
  {
    name: 'One Plus 3',
    width: 480,
    height: 853,
    type: 'jpeg',
  },
  {
    name: 'Samsung Galaxy S9+',
    width: 360,
    height: 740,
    type: 'jpeg',
  },
  {
    name: 'Samsung Galaxy S9',
    width: 360,
    height: 740,
    type: 'jpeg',
  },
  {
    name: 'Samsung Galaxy S8+',
    width: 360,
    height: 740,
    type: 'jpeg',
  },
  {
    name: 'Samsung Galaxy S8',
    width: 360,
    height: 740,
    type: 'jpeg',
  },
  {
    name: 'Samsung Galaxy S7 Edge',
    width: 360,
    height: 640,
    type: 'jpeg',
  },
  {
    name: 'Samsung Galaxy S7',
    width: 360,
    height: 640,
    type: 'jpeg',
  },
  {
    name: 'Nexus 9',
    width: 768,
    height: 1024,
    type: 'jpeg',
  },
  {
    name: 'Nexus 7 (2013)',
    width: 600,
    height: 960,
    type: 'jpeg',
  },
  {
    name: 'Samsung Galaxy Tab 10',
    width: 800,
    height: 1280,
    type: 'jpeg',
  },
  {
    name: 'Chromebook Pixel',
    width: 1280,
    height: 850,
    type: 'jpeg',
  },
];

module.exports = {
  devices,
};